name: Feature Request
description: Suggest an idea for WiingPong
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees:
  - cristianino
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for WiingPong!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (small change)
        - Medium (moderate change)
        - High (significant change)
        - Unknown
    validations:
      required: false

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      options:
        - label: Gameplay enhancement
        - label: Visual improvement
        - label: Audio enhancement
        - label: Performance optimization
        - label: Developer/Debug feature
        - label: Configuration option
        - label: Other

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
