name: Wii Build CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install devkitPro
      run: |
        sudo apt update
        sudo apt install -y wget curl build-essential
        
        # Use Docker approach as alternative since apt.devkitpro.org is having issues
        # Install via official devkitPro Docker image method
        wget https://github.com/devkitPro/docker/raw/master/devkitppc/Dockerfile -O devkitppc.dockerfile
        
        # Extract the installation commands from the Dockerfile
        # Install pacman manually from GitHub releases (latest working version)
        PACMAN_VERSION="1.0.2"
        PACMAN_URL="https://github.com/devkitPro/pacman/releases/download/v${PACMAN_VERSION}/devkitpro-pacman_${PACMAN_VERSION}-2_amd64.deb"
        
        # Download with retries
        for i in {1..3}; do
          curl -L "$PACMAN_URL" -o devkitpro-pacman.deb && break
          echo "Download attempt $i failed, retrying..."
          sleep 2
        done
        
        # Verify download
        if [ ! -f devkitpro-pacman.deb ] || [ ! -s devkitpro-pacman.deb ]; then
          echo "Failed to download devkitpro-pacman.deb"
          exit 1
        fi
        
        # Install with dependency resolution
        sudo dpkg -i devkitpro-pacman.deb || sudo apt-get install -f -y
        
        # Verify installation
        which dkp-pacman || { echo "dkp-pacman not found after installation"; exit 1; }
        
        # Install development packages
        sudo dkp-pacman -Sy --noconfirm
        sudo dkp-pacman -S --noconfirm devkitPPC libogc grrlib

    - name: Setup environment
      run: |
        echo "/opt/devkitpro/devkitPPC/bin" >> $GITHUB_PATH
        echo "/opt/devkitpro/tools/bin" >> $GITHUB_PATH
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITPPC=/opt/devkitpro/devkitPPC" >> $GITHUB_ENV

    - name: Build with Make
      run: |
        make clean
        make -j$(nproc)

    - name: Create package
      run: make package

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WiingPong-build-${{ github.sha }}
        path: |
          WiingPong.elf
          WiingPong.dol
          apps/

    - name: Install cppcheck
      run: sudo apt-get update && sudo apt-get install -y cppcheck

    - name: Run static analysis (cppcheck)
      run: |
        cppcheck \
          --enable=all \
          --std=c++11 \
          --platform=unix32 \
          --suppress=missingIncludeSystem \
          --suppress=unusedFunction \
          --error-exitcode=0 \
          --quiet \
          source/
      continue-on-error: true