name: Wii Build CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install devkitPro
      run: |
        sudo apt update
        sudo apt install -y wget curl build-essential software-properties-common
        
        # Import devkitPro public key correctly
        wget -qO- https://apt.devkitpro.org/devkitpro-pub.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/devkitpro.gpg
        
        # Add devkitPro repository
        echo "deb https://apt.devkitpro.org stable main" | sudo tee /etc/apt/sources.list.d/devkitpro.list
        
        # Update and install devkitpro-pacman
        sudo apt update
        sudo apt install -y devkitpro-pacman
        
        # Verify installation and install development packages
        which dkp-pacman || { echo "dkp-pacman not found after installation"; exit 1; }
        sudo dkp-pacman -Sy
        sudo dkp-pacman -S --noconfirm devkitPPC libogc grrlib

    - name: Setup environment
      run: |
        echo "/opt/devkitpro/devkitPPC/bin" >> $GITHUB_PATH
        echo "/opt/devkitpro/tools/bin" >> $GITHUB_PATH
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITPPC=/opt/devkitpro/devkitPPC" >> $GITHUB_ENV

    - name: Build with Make
      run: |
        make clean
        make -j$(nproc)

    - name: Create package
      run: make package

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WiingPong-build-${{ github.sha }}
        path: |
          WiingPong.elf
          WiingPong.dol
          apps/

    - name: Install cppcheck
      run: sudo apt-get update && sudo apt-get install -y cppcheck

    - name: Run static analysis (cppcheck)
      run: |
        cppcheck \
          --enable=all \
          --std=c++11 \
          --platform=unix32 \
          --suppress=missingIncludeSystem \
          --suppress=unusedFunction \
          --error-exitcode=0 \
          --quiet \
          source/
      continue-on-error: true